using System;
using System.Configuration;
using Oracle.ManagedDataAccess.Client;

namespace Wayfinder.API.Services
{
    /// <summary>
    /// Oracle database context for managing connections.
    /// Each instance should be used within a single thread/request context.
    /// Use with 'using' statement to ensure proper disposal.
    /// </summary>
    public class OracleDbContext : IDisposable
    {
        private readonly string _connectionString;
        private OracleConnection _connection;
        private bool _disposed = false;
        private readonly object _lock = new object();

        public OracleDbContext()
        {
            _connectionString = ConfigurationManager.ConnectionStrings["OracleDbContext"]?.ConnectionString
                ?? throw new ConfigurationErrorsException("Oracle connection string not found");
        }

        public OracleDbContext(string connectionString)
        {
            _connectionString = connectionString;
        }

        public OracleConnection GetConnection()
        {
            lock (_lock)
            {
                if (_disposed)
                {
                    throw new ObjectDisposedException(nameof(OracleDbContext));
                }

                if (_connection == null)
                {
                    _connection = new OracleConnection(_connectionString);
                }

                if (_connection.State != System.Data.ConnectionState.Open)
                {
                    _connection.Open();
                }

                return _connection;
            }
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            lock (_lock)
            {
                if (!_disposed)
                {
                    if (disposing)
                    {
                        if (_connection != null)
                        {
                            if (_connection.State == System.Data.ConnectionState.Open)
                            {
                                _connection.Close();
                            }
                            _connection.Dispose();
                            _connection = null;
                        }
                    }
                    _disposed = true;
                }
            }
        }

        /// <summary>
        /// Initialize database schema
        /// </summary>
        public static void InitializeDatabase()
        {
            var connectionString = ConfigurationManager.ConnectionStrings["OracleDbContext"]?.ConnectionString;
            if (string.IsNullOrEmpty(connectionString))
            {
                throw new ConfigurationErrorsException("Oracle connection string not found");
            }

            using (var connection = new OracleConnection(connectionString))
            {
                connection.Open();

                // Create Users table
                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE USERS (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            EMAIL VARCHAR2(255) NOT NULL UNIQUE,
                            PASSWORD_HASH VARCHAR2(255) NOT NULL,
                            COLOR1 VARCHAR2(7),
                            COLOR2 VARCHAR2(7),
                            COLOR3 VARCHAR2(7),
                            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            UPDATED_AT TIMESTAMP
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                // Create Tasks table
                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE TASKS (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            TITLE VARCHAR2(255) NOT NULL,
                            USER_ID NUMBER NOT NULL,
                            LAST_FINISHED_DATE TIMESTAMP,
                            REFRESH_INTERVAL NUMBER DEFAULT 1,
                            ALERT_THRESHOLD_PERCENTAGE NUMBER DEFAULT 80,
                            IS_ACTIVE NUMBER(1) DEFAULT 1,
                            INITIAL_REFRESH_INTERVAL NUMBER DEFAULT 1,
                            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            UPDATED_AT TIMESTAMP,
                            CONSTRAINT FK_TASKS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                // Create Tags table
                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE TAGS (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            NAME VARCHAR2(100) NOT NULL,
                            TASK_ID NUMBER NOT NULL,
                            CONSTRAINT FK_TAGS_TASK FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID) ON DELETE CASCADE
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                // Create TaskTags table (many-to-many relationship)
                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE TASK_TAGS (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            TASK_ID NUMBER NOT NULL,
                            TAG_ID NUMBER NOT NULL,
                            CONSTRAINT FK_TASKTAGS_TASK FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID) ON DELETE CASCADE,
                            CONSTRAINT FK_TASKTAGS_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID) ON DELETE CASCADE,
                            CONSTRAINT UQ_TASKTAGS UNIQUE (TASK_ID, TAG_ID)
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                // Create Records table
                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE RECORDS (
                            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            TASK_ID NUMBER NOT NULL,
                            FINISHED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            STATUS VARCHAR2(50) NOT NULL,
                            CONSTRAINT FK_RECORDS_TASK FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID) ON DELETE CASCADE
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                // Create indexes
                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TASKS_USER_ID ON TASKS(USER_ID)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX IDX_TAGS_TASK_ID ON TAGS(TASK_ID)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");

                ExecuteNonQuery(connection, @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE INDEX IDX_RECORDS_TASK_ID ON RECORDS(TASK_ID)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN RAISE; END IF;
                    END;");
            }
        }

        private static void ExecuteNonQuery(OracleConnection connection, string sql)
        {
            using (var command = new OracleCommand(sql, connection))
            {
                command.ExecuteNonQuery();
            }
        }
    }
}
